# Generated by Django 3.1.3 on 2020-11-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercompany',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='direction',
            field=models.CharField(choices=[('IMP', 'Import'), ('IMP', 'Export')], max_length=20),
        ),
    ]
