# Generated by Django 3.1.3 on 2020-12-01 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_warehouse_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.country'),
            preserve_default=False,
        ),
    ]
