# Generated by Django 3.1.3 on 2020-12-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201209_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercompany',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='transportcompany',
            name='company_logo',
        ),
    ]
