# Generated by Django 3.1.3 on 2020-12-09 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201209_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercompany',
            name='published',
        ),
    ]
