# Generated by Django 3.1.3 on 2020-11-28 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('billing_address', models.CharField(max_length=40)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Seaport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('un_location_code', models.CharField(max_length=5)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
        migrations.CreateModel(
            name='TransportCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trucker_name', models.CharField(max_length=20)),
                ('billing_address', models.CharField(max_length=40)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_address', models.CharField(max_length=40)),
                ('ramp_on_site', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
                ('customer_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customercompany')),
            ],
        ),
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('imp', 'Import'), ('exp', 'Export')], max_length=20)),
                ('seaport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.seaport')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='TransportOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transportrequest')),
                ('trucker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transportcompany')),
            ],
        ),
    ]
