# Generated by Django 3.1.3 on 2020-12-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customercompany_mark_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercompany',
            name='mark_up',
            field=models.FloatField(default=0),
        ),
    ]
