# Generated by Django 3.1.3 on 2020-12-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201206_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercompany',
            name='company_logo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='transportcompany',
            name='company_logo',
            field=models.URLField(blank=True),
        ),
    ]
