# Generated by Django 3.1.3 on 2020-12-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_customercompany_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='quote_completed',
            field=models.BooleanField(default=False),
        ),
    ]
