# Generated by Django 3.1.3 on 2020-12-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201213_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercompany',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
